---
all:
  children:
    clickhouse:
      hosts:
        clickhouse-0.ru-central1.internal:
          ansible_host: 89.169.129.103

    vector:
      hosts:
        vector-0.ru-central1.internal:
          ansible_host: 89.169.135.244
        vector-1.ru-central1.internal:
          ansible_host: 89.169.144.4
